# Generated by Django 2.1.2 on 2018-10-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='University',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=300, unique=True)),
				('average_gpa', models.FloatField()),
				('average_sat_score', models.IntegerField()),
				('sat_percentile_25', models.IntegerField()),
				('sat_percentile_75', models.IntegerField()),
				('average_act_score', models.IntegerField()),
			],
		),
	]
