# Generated by Django 2.1.2 on 2018-10-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCirculars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('university_percentage', models.FloatField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'Universities'},
        ),
        migrations.AddField(
            model_name='extracirculars',
            name='university',
            field=models.ForeignKey(on_delete='cascade', to='Matcher.University'),
        ),
    ]
