# Generated by Django 2.1.2 on 2018-10-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matcher', '0002_auto_20181007_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracirculars',
            name='university',
            field=models.ForeignKey(on_delete='cascade', related_name='extras', to='Matcher.University'),
        ),
    ]
